### ISSUE TITLE
Windows 7 issues

### ISSUE THREAD

**Issue by dy** [clehner/git-ssb#11]
My 2¢ of switching to git-ssb.

## 1. Not found repo

Trying to clone [git-ssb repo](https://git.scuttlebot.io/%25n92DiQh7ietE%2BR%2BX%2FI403LQoyf2DtR3WQfCkDKlheQU%3D.sha256) to post issues.

```sh
$ git clone ssb://%n92DiQh7ietE+R+X/I403LQoyf2DtR3WQfCkDKlheQU=.sha256
Cloning into 'I403LQoyf2DtR3WQfCkDKlheQU=.sha256'...
Repo not found with ID %n92DiQh7ietE+R+X/I403LQoyf2DtR3WQfCkDKlheQU=.sha256
```

What does that mean? Is that ok? Is the repo not available _now_ or there is some internal error?

## 2. Not found issues

Cloning that via https is ok, but cannot get access to issues. Is that due to **1.**?

```sh
$ git clone https://git.scuttlebot.io/%25n92DiQh7ietE%2BR%2BX%2FI403LQoyf2DtR3WQfCkDKlheQU%3D.sha256 git-ssb
Cloning into 'git-ssb'...

$ cd git-ssb/

$ git ssb issues
unable to find git-ssb repo
```

## 3. Pushing to remote ssb gives EPIPE error

```sh
$ git init
Initialized empty Git repository in C:/projects/ssb-test/.git/

$ git ssb create ssb
Created repo: ssb://%J7zkHwkuAthDYHvfK7d3rZKyjEQY8dzemDrV4VJYTaY=.sha256 (ssb-test)
Added remote: ssb

$ touch .gitignore

$ git add -A
$ git commit -m "Init"

$ git push ssb master
Counting objects: 3, done.
Writing objects: 100% (3/3), 217 bytes | 217.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
Decoding objects: 100% (3/3)
Pushing blobs...
Published %Sc51YNj6eENcuyz04WJ1HQUwezC9sRoFl9AmYwCS+Ek=.sha256
C:\Users\dmitry\AppData\Roaming\npm\node_modules\git-ssb\node_modules\git-remote-ssb\git-remote-ssb:58
        if (err) throw err
                 ^

Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:780:25)
    at Socket._write (net.js:799:8)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:717:40)
    at C:\Users\dmitry\AppData\Roaming\npm\node_modules\git-ssb\node_modules\stream-to-pull-stream\index.js:76:18
    at C:\Users\dmitry\AppData\Roaming\npm\node_modules\git-ssb\node_modules\pull-git-remote-helper\index.js:469:11
    at C:\Users\dmitry\AppData\Roaming\npm\node_modules\git-ssb\node_modules\pull-git-remote-helper\lib\pkt-line.js:31:9

To ssb://%J7zkHwkuAthDYHvfK7d3rZKyjEQY8dzemDrV4VJYTaY=.sha256
 * [new branch]      master -> master
error: failed to push some refs to 'ssb://%J7zkHwkuAthDYHvfK7d3rZKyjEQY8dzemDrV4VJYTaY=.sha256'
```

So how to post an issue, eg. this, to remote git-ssb?

**Comment by hackergrrl** [comment]
Thanks for writing back!

1. You'll need to surround the `ssb://` URI with single quotes, to keep your shell from interpreting some characters as control chars.
2. You might have to close via ssb:// in order to see issues.
3. Is `sbot` running?

**Comment by dy** [comment]
1., 2.:

```sh
$ git clone 'ssb://%n92DiQh7ietE+R+X/I403LQoyf2DtR3WQfCkDKlheQU=.sha256' git-ssb
Cloning into 'git-ssb'...
Repo not found with ID %n92DiQh7ietE+R+X/I403LQoyf2DtR3WQfCkDKlheQU=.sha256

$ git clone "ssb://%n92DiQh7ietE+R+X/I403LQoyf2DtR3WQfCkDKlheQU=.sha256" git-ssb
Cloning into 'git-ssb'...
Repo not found with ID %n92DiQh7ietE+R+X/I403LQoyf2DtR3WQfCkDKlheQU=.sha256
```

3. Sure, `sbot` error is understandable `Could not connect to sbot`

**Comment by hackergrrl** [comment]
What's on npm is an older version of git-ssb, I wonder if you'll need the latest (which is on ssb-npm). If you're OK with another piece of legwork, you can follow [this ssb-npm guide](https://github.com/noffle/ssb-npm-101) and then reinstall git-ssb with `ssb-npm i -g git-ssb`.

(I could see this as feeling pretty difficult to get started. We're still a pretty young community, and lots of things are still rough around the edges.)

**Comment by dy** [comment]
`ssb-npm` package is not in npm for now. I don't see it in github neither in git.scuttlebot.io. How to work that around?

**Comment by hackergrrl** [comment]
@dy Follow the guide I linked to in my above post; it'll walk you through it. ssb-npm is on ssb itself, so there's a bootstrapping process to follow.
