### ISSUE TITLE
crashes on page load

### ISSUE THREAD

**Issue by wanderer** [clehner/git-ssb#2]
> git-ssb-web@1.7.0 start /home/null/code/git-ssb-web
> node server.js

Listening on http://localhost:7718/
GET /
GET /styles.css
/home/null/code/git-ssb-web/about.js:89
      var c = msg.value.content
                       ^

TypeError: Cannot read property 'content' of undefined
    at /home/null/code/git-ssb-web/about.js:89:24
    at /home/null/code/git-ssb-web/node_modules/pull-stream/sinks/drain.js:24:37
    at PacketStreamSubstream.weird.read (/home/null/code/git-ssb-web/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (/home/null/code/git-ssb-web/node_modules/packet-stream/index.js:192:12)
    at PacketStream.write (/home/null/code/git-ssb-web/node_modules/packet-stream/index.js:123:41)
    at /home/null/code/git-ssb-web/node_modules/muxrpc/pull-weird.js:56:15
    at /home/null/code/git-ssb-web/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/null/code/git-ssb-web/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/null/code/git-ssb-web/node_modules/packet-stream-codec/index.js:107:11)
    at drain (/home/null/code/git-ssb-web/node_modules/pull-reader/index.js:39:14)

**Comment by wanderer** [comment]
opps! moving to git-ssb-web
