### ISSUE TITLE
error while loading git-ssb-web

### ISSUE THREAD

**Issue by myf** [clehner/git-ssb#6]
there are only a few items on the page while trying to access git-ssb-web, with the following error code:
```
UsageError
Error
    at ZE (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/zerr/index.js:11:42)
    at ZError (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/zerr/index.js:13:14)
    at Object.linksOpts (/home/myf/.npm-packages/lib/node_modules/scuttlebot/lib/validators.js:166:14)
    at validate (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/muxrpc-validation/index.js:130:15)
    at EventEmitter.<anonymous> (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/muxrpc-validation/index.js:91:17)
    at EventEmitter.hooked [as links] (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/hoox/index.js:10:15)
    at /home/myf/.ssb_take3/node_modules/git-ssb-web/lib/about.js:46:12
    at run (/home/myf/.ssb_take3/node_modules/git-ssb-web/node_modules/asyncmemo/index.js:33:8)
    at /home/myf/.ssb_take3/node_modules/git-ssb-web/node_modules/asyncmemo/index.js:26:9
    at getAbout (/home/myf/.ssb_take3/node_modules/git-ssb-web/lib/about.js:91:5)
```

**Comment by clehner** [comment]
I broke it with %9hoI9VXb7N0M286acIIESbs2/M9QlcbH0lgHu34F0FM=.sha256, and haven't fixed it yet. Sorry

**Comment by bdionne** [comment]
I'm seeing something similar when I access `localhost:7718`

````
Error
    at ZE (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/zerr/index.js:11:42)
    at ZError (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/zerr/index.js:13:14)
    at Object.linksOpts (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/scuttlebot/lib/validators.js:166:14)
    at validate (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc-validation/index.js:130:15)
    at Object.<anonymous> (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc-validation/index.js:91:17)
    at Object.hooked (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/hoox/index.js:10:15)
    at Object.localCall (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/local-api.js:31:31)
    at Object.<anonymous> (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/local-api.js:37:22)
    at PacketStreamSubstream.stream.read (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/stream.js:67:23)
    at PacketStream._onstream (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream/index.js:230:11)
````
